version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - /var/lib/zookeeper/data
    ports:
      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
    volumes:
      - /var/lib/kafka/data
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3306:3306
    command: --authentication_policy=caching_sha2_password
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/script.sql
