[package]
org = "lakshanweerasinghe"
name = "load_data_from_csv"
version = "0.1.0"
distribution = "2201.8.2"

[build-options]
observabilityIncluded = true

[persist]
datastore = "inmemory"
module = "load_data_from_csv.leads"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.2.0"

