[package]
org = "etl_samples"
name = "extract_customer_orders"
version = "0.1.0"
distribution = "2201.8.2"

[persist]
datastore = "mysql"
module = "customerOrders"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.0"

